In [33]:
import pandas as pd
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import requests
import json
from pprint import pprint

# Import API key
from api_keys import d_key

### Extract CSVs into DataFrames

In [34]:
# Creates lists for data to be stored 
id = []
name = []
weight = []
height = []
bred_for = []
breed_group = []
url = r"https://api.thedogapi.com/v1/breeds"
response = requests.get(url).json()

pprint(response[0])

{'bred_for': 'Small rodent hunting, lapdog',
 'breed_group': 'Toy',
 'height': {'imperial': '9 - 11.5', 'metric': '23 - 29'},
 'id': 1,
 'image': {'height': 1199,
           'id': 'BJa4kxc4X',
           'url': 'https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg',
           'width': 1600},
 'life_span': '10 - 12 years',
 'name': 'Affenpinscher',
 'origin': 'Germany, France',
 'reference_image_id': 'BJa4kxc4X',
 'temperament': 'Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',
 'weight': {'imperial': '6 - 13', 'metric': '3 - 6'}}

In [35]:
#x=0
#while (x) < 20:
#    #pprint(response[x])
#    print(response[x]['id'])
#    if 'bred_for' in response[x]:
#        print(response[x]['bred_for'])
#        print('....')
#    else:
#        print("null")
#    if 'breed_group' in response[x]:
#        print(response[x]['breed_group'])
#        print('....')
#    else:
#        print("null")
#    x += 1

In [36]:

for i in response:
    if i['id'] == 21: break 
    print(f"{i['id']}, breed = {i['name']}, weight(Kg) {i['weight']['metric']}, height (cm) {i['height']['metric']}")

1, breed = Affenpinscher, weight(Kg) 3 - 6, height (cm) 23 - 29
2, breed = Afghan Hound, weight(Kg) 23 - 27, height (cm) 64 - 69
3, breed = African Hunting Dog, weight(Kg) 20 - 30, height (cm) 76
4, breed = Airedale Terrier, weight(Kg) 18 - 29, height (cm) 53 - 58
5, breed = Akbash Dog, weight(Kg) 41 - 54, height (cm) 71 - 86
6, breed = Akita, weight(Kg) 29 - 52, height (cm) 61 - 71
7, breed = Alapaha Blue Blood Bulldog, weight(Kg) 25 - 41, height (cm) 46 - 61
8, breed = Alaskan Husky, weight(Kg) 17 - 23, height (cm) 58 - 66
9, breed = Alaskan Malamute, weight(Kg) 29 - 45, height (cm) 58 - 64
10, breed = American Bulldog, weight(Kg) 27 - 54, height (cm) 56 - 69
11, breed = American Bully, weight(Kg) 14 - 68, height (cm) 36 - 43
12, breed = American Eskimo Dog, weight(Kg) 9 - 18, height (cm) 38 - 48
13, breed = American Eskimo Dog (Miniature), weight(Kg) 3 - 5, height (cm) 23 - 30
14, breed = American Foxhound, weight(Kg) 29 - 34, height (cm) 53 - 71
15, breed = American Pit Bull Terrier, weight(Kg) 14 - 27, height (cm) 43 - 53
16, breed = American Staffordshire Terrier, weight(Kg) 23 - 27, height (cm) 43 - 48
17, breed = American Water Spaniel, weight(Kg) 11 - 20, height (cm) 38 - 46
18, breed = Anatolian Shepherd Dog, weight(Kg) 36 - 68, height (cm) 69 - 74
19, breed = Appenzeller Sennenhund, weight(Kg) 22 - 25, height (cm) 51 - 56

In [37]:
#appending the data to the empty lists 
for i in response:
    id.append(i["id"])
    name.append(i["name"])
    weight.append(i["weight"]['metric'])
    height.append(i["height"]['metric'])
    if 'breed_group' in i:
        breed_group.append(i['breed_group'])
    else:
        breed_group.append('Unknown')
    if 'bred_for' in i:
        bred_for.append(i['bred_for'])
    else:
        bred_for.append('Unknown')
        
#    bred_for = []
#breed_group = []
print(len(bred_for))
print(len(breed_group))
# create a dictionary for establishing dataframe
dog_data = {
    "ID":id,
    "Breed":name,
    "Weight": weight,
    "Height": height,
    "breed_group": breed_group,
    "bred_for":bred_for,
}

dog_df = pd.DataFrame(dog_data)

dog_df

172
172

,ID,Breed,Weight,Height,breed_group,bred_for
0,1,Affenpinscher,3 - 6,23 - 29,Toy,"Small rodent hunting, lapdog"
1,2,Afghan Hound,23 - 27,64 - 69,Hound,Coursing and hunting
2,3,African Hunting Dog,20 - 30,76,Unknown,A wild pack animal
3,4,Airedale Terrier,18 - 29,53 - 58,Terrier,"Badger, otter hunting"
4,5,Akbash Dog,41 - 54,71 - 86,Working,Sheep guarding
...,...,...,...,...,...,...
167,259,Wire Fox Terrier,7 - 9,33 - 41,Unknown,"Vermin hunting, fox bolting"
168,260,Wirehaired Pointing Griffon,20 - 32,51 - 61,Sporting,"Gundog, ""swamp-tromping"", Flushing, pointing, ..."
169,261,Wirehaired Vizsla,20 - 29,55 - 64,Sporting,Unknown
170,262,Xoloitzcuintli,4 - 14,25 - 58,Non-Sporting,Unknown
171,264,Yorkshire Terrier,2 - 3,20 - 23,Toy,Small vermin hunting

In [38]:
intelligence = "Resources/intelligence.csv"
intelligence_df = pd.read_csv(intelligence)
intelligence_df.head(30)

,Breed,Classification,obey,reps_lower,reps_upper
0,Border Collie,Brightest Dogs,95%,1,4
1,Poodle,Brightest Dogs,95%,1,4
2,German Shepherd,Brightest Dogs,95%,1,4
3,Golden Retriever,Brightest Dogs,95%,1,4
4,Doberman Pinscher,Brightest Dogs,95%,1,4
5,Shetland Sheepdog,Brightest Dogs,95%,1,4
6,Labrador Retriever,Brightest Dogs,95%,1,4
7,Papillon,Brightest Dogs,95%,1,4
8,Rottweiler,Brightest Dogs,95%,1,4
9,Australian Cattle Dog,Brightest Dogs,95%,1,4
10,Pembroke Welsh Corgi,Excellent Working Dogs,85%,5,15
11,Miniature Schnauzer,Excellent Working Dogs,85%,5,15
12,English Springer Spaniel,Excellent Working Dogs,85%,5,15
13,Belgian Shepherd Dog (Tervuren),Excellent Working Dogs,85%,5,15
14,Schipperke,Excellent Working Dogs,85%,5,15
15,Belgian Sheepdog,Excellent Working Dogs,85%,5,15
16,Collie,Excellent Working Dogs,85%,5,15
17,Keeshond,Excellent Working Dogs,85%,5,15
18,German Shorthaired Pointer,Excellent Working Dogs,85%,5,15
19,Flat-Coated Retriever,Excellent Working Dogs,85%,5,15
20,English Cocker Spaniel,Excellent Working Dogs,85%,5,15
21,Standard Schnauzer,Excellent Working Dogs,85%,5,15
22,Brittany,Excellent Working Dogs,85%,5,15
23,Cocker Spaniel,Excellent Working Dogs,85%,5,15
24,Weimaraner,Excellent Working Dogs,85%,5,15
25,Belgian Malinois,Excellent Working Dogs,85%,5,15
26,Bernese Mountain Dog,Excellent Working Dogs,85%,5,15
27,Pomeranian,Excellent Working Dogs,85%,5,15
28,Irish Water Spaniel,Excellent Working Dogs,85%,5,15
29,Vizsla,Excellent Working Dogs,85%,5,15

In [43]:
# using merge function by setting how='inner'
final_df = pd.merge(intelligence_df, dog_df, 
                   on='Breed', 
                   how='inner')
final_df

,Breed,Classification,obey,reps_lower,reps_upper,ID,Weight,Height,breed_group,bred_for
0,Border Collie,Brightest Dogs,95%,1,4,50,14 - 20,46 - 56,Herding,Sheep herder
1,Golden Retriever,Brightest Dogs,95%,1,4,121,25 - 34,55 - 61,Sporting,Retrieving
2,Doberman Pinscher,Brightest Dogs,95%,1,4,94,30 - 40,61 - 71,Working,Guardian
3,Shetland Sheepdog,Brightest Dogs,95%,1,4,221,14,33 - 41,Herding,Sheep herding
4,Labrador Retriever,Brightest Dogs,95%,1,4,149,25 - 36,55 - 62,Sporting,Water retrieving
...,...,...,...,...,...,...,...,...,...,...
96,Pekingese,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,183,6,15 - 23,Toy,Lapdog
97,Bloodhound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,45,36 - 50,58 - 69,Hound,Trailing
98,Chow Chow,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,81,18 - 32,43 - 51,Non-Sporting,"Guardian, cart pulling, hunting"
99,Basenji,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,28,10 - 11,41 - 43,Hound,Hunting
100,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,2,23 - 27,64 - 69,Hound,Coursing and hunting

In [50]:
final_df2 = final_df[['Breed','Classification','Weight','Height','breed_group', 'bred_for']]
final_df2.head(30)

,Breed,Classification,Weight,Height,breed_group,bred_for
0,Border Collie,Brightest Dogs,14 - 20,46 - 56,Herding,Sheep herder
1,Golden Retriever,Brightest Dogs,25 - 34,55 - 61,Sporting,Retrieving
2,Doberman Pinscher,Brightest Dogs,30 - 40,61 - 71,Working,Guardian
3,Shetland Sheepdog,Brightest Dogs,14,33 - 41,Herding,Sheep herding
4,Labrador Retriever,Brightest Dogs,25 - 36,55 - 62,Sporting,Water retrieving
5,Papillon,Brightest Dogs,1 - 5,20 - 28,Toy,Lapdog
6,Rottweiler,Brightest Dogs,34 - 50,56 - 69,Working,"Cattle drover, guardian, draft"
7,Australian Cattle Dog,Brightest Dogs,20 - 28,43 - 51,Herding,"Cattle herding, herding trials"
8,Pembroke Welsh Corgi,Excellent Working Dogs,11 - 14,25 - 30,Herding,Driving stock to market in northern Wales
9,Miniature Schnauzer,Excellent Working Dogs,5 - 9,30 - 36,Terrier,Ratting
10,English Springer Spaniel,Excellent Working Dogs,16 - 23,48 - 51,Sporting,"Bird flushing, retrieving"
11,Schipperke,Excellent Working Dogs,5 - 7,25 - 33,Non-Sporting,Barge watchdog
12,Keeshond,Excellent Working Dogs,16 - 20,43 - 46,Non-Sporting,Barge watchdog
13,German Shorthaired Pointer,Excellent Working Dogs,20 - 32,53 - 64,Sporting,General hunting
14,Standard Schnauzer,Excellent Working Dogs,14 - 23,44 - 50,Working,"Ratting, guarding"
15,Brittany,Excellent Working Dogs,14 - 20,44 - 52,Sporting,"Pointing, retrieving"
16,Cocker Spaniel,Excellent Working Dogs,9 - 14,36 - 38,Sporting,"Bird flushing, retrieving"
17,Weimaraner,Excellent Working Dogs,25 - 41,58 - 69,Sporting,Large game trailing and versatile gundog
18,Belgian Malinois,Excellent Working Dogs,18 - 36,56 - 66,Herding,Stock herding
19,Bernese Mountain Dog,Excellent Working Dogs,29 - 54,58 - 70,Working,Draft work
20,Pomeranian,Excellent Working Dogs,1 - 3,20 - 30,Toy,Companion
21,Vizsla,Excellent Working Dogs,23 - 29,53 - 61,Sporting,Pointing and trailing
22,Cardigan Welsh Corgi,Excellent Working Dogs,11 - 17,27 - 32,Herding,Cattle droving
23,Chesapeake Bay Retriever,Above Average Working Dogs,25 - 36,53 - 66,Sporting,Water Retriever
24,Puli,Above Average Working Dogs,11 - 16,41 - 43,Herding,Herding
25,Yorkshire Terrier,Above Average Working Dogs,2 - 3,20 - 23,Toy,Small vermin hunting
26,Giant Schnauzer,Above Average Working Dogs,29 - 41,60 - 70,Working,"Herding, guarding"
27,Airedale Terrier,Above Average Working Dogs,18 - 29,53 - 58,Terrier,"Badger, otter hunting"
28,Bouvier des Flandres,Above Average Working Dogs,32 - 50,60 - 70,Herding,Cattle herding
29,Border Terrier,Above Average Working Dogs,5 - 7,28 - 41,Terrier,"Fox bolting, ratting"

In [24]:
# Classification_list = pd.DataFrame(intelligence_df['Classification'].unique())
# Classification_list

                                                  0
0                                    Brightest Dogs
1                            Excellent Working Dogs
2                        Above Average Working Dogs
3            Average Working/Obedience Intelligence
4               Fair Working/Obedience Intelligence
5  Lowest Degree of Working/Obedience Intelligence

### Transform premise DataFrame

### Transform county DataFrame

### Create database connection

### Load DataFrames into database